### ISSUE TITLE
CSGO update broke IsAlive

### ISSUE THREAD

**Issue by bbbbbzzzz** [anarh1st47/CSGOSimple#10]
bool C_BasePlayer::IsAlive()
{
	return m_lifeState() == LIFE_ALIVE;
}
Debugger shows error here

**Comment by anarh1st47** [comment]
No error here, netvar is ok, probably u didnt check is player nullptr before call it. Show ur error

**Comment by bbbbbzzzz** [comment]
but default csgo simple began crashing after today update, debugger shows error in IsAlive like cannot read memory in address

**Comment by bbbbbzzzz** [comment]
woops im noobie , sorry for my mistake, everything ok
