### ISSUE TITLE
ESP Bug

### ISSUE THREAD

**Issue by bbbbbzzzz** [anarh1st47/CSGOSimple#13]
http://prntscr.com/kq2jjm default esp

**Comment by bbbbbzzzz** [comment]
idk im just render watermark
`
	static float hue;
	hue += 0.005f;if (hue > 1.f)hue = 0.f;
	Render::Get().RenderText("test", 150, 10, 14.f, Color::FromHSB(hue, 1.f, 1.f));`
and getting this visual bugs

**Comment by anarh1st47** [comment]
could u show it on video? ive tried and cannot reproduce

**Comment by bbbbbzzzz** [comment]
`void Visuals::AddToDrawList() {
	if (!g_EngineClient->IsInGame() || !g_LocalPlayer)
		return;

	for (auto i = 1; i <= g_EntityList->GetHighestEntityIndex(); ++i) {
		auto entity = C_BaseEntity::GetEntityByIndex(i);
		if (!entity)
			continue;

		if (i < 65) {
			auto player = Player();
			if (player.Begin((C_BasePlayer*)entity)) {
				if (g_Options.esp_player_snaplines) player.RenderSnapline();
				if (g_Options.esp_player_boxes)     player.RenderBox();
				if (g_Options.esp_player_weapons)   player.RenderWeaponName();
				if (g_Options.esp_player_names)     player.RenderName();
				if (g_Options.esp_player_health)    player.RenderHealth();
				if (g_Options.esp_player_armour)    player.RenderArmour();
				if (g_Options.esp_player_lbyupdates)player.RenderLby();
			}
		}
		else if (g_Options.esp_dropped_weapons && entity->IsWeapon())
			RenderWeapon(static_cast<C_BaseCombatWeapon*>(entity));
		else if (g_Options.esp_dropped_weapons && entity->IsDefuseKit())
			RenderDefuseKit(entity);
		else if (entity->IsPlantedC4() && g_Options.esp_planted_c4)
			RenderPlantedC4(entity);
	}
	static float hue;
	hue += 0.005f; if (hue > 1.f)hue = 0.f;

	auto clr = Color::FromHSB(hue, 1.f, 1.f);
	Render::Get().RenderText("test", 150, 10, 14.f, clr);
`

**Comment by anarh1st47** [comment]
tried a lot of watermarks, ur code too, no bug for me. I will push watermark example, cuz another guy asked me for watermark too(in telegram)

**Comment by anarh1st47** [comment]
https://github.com/anarh1st47/CSGOSimple/blob/05b3387ef8fa9a236f1fd6b62053cb6dde7343e5/CSGOSimple/render.cpp#L64-L65

Also same result(no this bug) if using hue

**Comment by bbbbbzzzz** [comment]
idk maybe because using HSB, maybe because my PC

**Comment by anarh1st47** [comment]
Can u clone clean repo and test it? replace color with hue and test? worked nice for me
