### ISSUE TITLE
[hw] how i can make esp font like on screenshots?

### ISSUE THREAD

**Issue by bbbbbzzzz** [anarh1st47/CSGOSimple#15]
https://camo.githubusercontent.com/fb8f24895cf1efce541fc1d30e27bb246f6caa4b/68747470733a2f2f692e696d6775722e636f6d2f4e524a3465326e2e706e67

**Comment by anarh1st47** [comment]
dont use droidsand font for esp rendering

**Comment by bbbbbzzzz** [comment]
> dont use droidsand font for esp rendering

what? why? i want see font like on mark's screenshots

**Comment by anarh1st47** [comment]
anarh1st47/csgosimple setting droidsans as imgui default font, MarkHC used another one(dont remember which), u could set any font what u want for specific elements rendering, c+p MarkHC's one. Not an issue and basic imgui(not csgosimple)question, so closing
