### ISSUE TITLE
m_flFlashDuration working ?

### ISSUE THREAD

**Issue by SrMilton** [anarh1st47/CSGOSimple#2]
Self explaining title

**Comment by Vladislavik36** [comment]
it works.

**Comment by anarh1st47** [comment]
Explain if you have some issue with it

**Comment by SrMilton** [comment]
I was trying to set m_flFlashDuration = 0

**Comment by anarh1st47** [comment]
Why r u setting it? i think thats wrong way

**Comment by SrMilton** [comment]
Trying to do a noflash, Is there another way to do this ?

**Comment by SrMilton** [comment]
Thanks but my problem was another, I'm so stupid
