### ISSUE TITLE
CCSWeaponInfo is outdated

### ISSUE THREAD

**Issue by bbbbbzzzz** [anarh1st47/CSGOSimple#9]
^

**Comment by anarh1st47** [comment]
u might try this:

`#pragma pack(push, 1)
class CCSWeaponInfo { //xSeeker
public:
	int8_t pad0[20];
	int32_t iMaxClip1;
	int8_t pad1[12];
	int32_t iMaxReservedAmmo;
	int8_t pad2[96];
	char* szHudName;
	char* szWeaponName;
	int8_t pad3[56];
	int32_t iWeaponType;
	int8_t pad4[4];
	int32_t iWeaponPrice;
	int32_t iKillAward;
	int8_t pad5[20];
	uint8_t bFullAuto;
	int8_t pad6[3];
	int32_t iDamage;
	float_t flArmorRatio;
	int32_t iBullets;
	float_t flPenetration;
	int8_t pad7[8];
	float_t flRange;
	float_t flRangeModifier;
	int8_t pad8[16];
	uint8_t bHasSilencer;
	int8_t pad9[15];
	float_t flSpread;
	float_t flSpreadAlt;
	int8_t pad10[76];
	int32_t iRecoilSeed;
	int8_t pad11[32];
};`

**Comment by bbbbbzzzz** [comment]
this one old too

**Comment by anarh1st47** [comment]
im using it(from comment) in another project(szWeaponName, WeaponType, flRange, etc) and it works perfectly. What u have problem with?

**Comment by anarh1st47** [comment]
Use issue #5 comments if have some problems with this weaponinfo
